PISD-226 Criar entidade de classificação abdominais e popular a tabela.
ToGatherGroup/sensei pull request #50
Opened 2024-06-10 00:15 UTC by MaiaraSilva

2024-06-10 03:09 UTC, DenilsonMarcio requested changes

2024-06-10 03:09 UTC, DenilsonMarcio commented on src/main/java/com/togather/sensei/models/classificacoes/ClassificacaoAbdominaisModel.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
Testou a geração dos dados? Acredito que ao utilizar o GeneratedValue para gerar talvez de erro no build.

2024-06-11 23:21 UTC, DenilsonMarcio approved these changes

2024-06-13 02:57 UTC, Michel-Machado approved these changes

2024-06-13 11:14 UTC, merged