PISD-272 Criar endpoint para dados qualitativos
ToGatherGroup/sensei pull request #60
Opened 2024-07-04 12:50 UTC by MaiaraSilva

2024-07-04 13:54 UTC, Michel-Machado approved these changes

2024-07-04 21:33 UTC, DenilsonMarcio requested changes

2024-07-04 21:33 UTC, DenilsonMarcio commented on src/main/java/com/togather/sensei/repositories/AtletaRepository.java
> +    @Query(nativeQuery = true, value = "SELECT sexo, nascimento FROM atleta_tb WHERE atleta_id = :atletaId")
"atleta_id" e um atributo existente dentro da tabela "atleta_tb" ? não seria somente "id"?

2024-07-10 01:24 UTC, DenilsonMarcio approved these changes

2024-07-10 13:28 UTC, merged